### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ezurechan** [ezurechan/furima-38118#21]
自身のフリマアプリのURL | https://furima-38118.herokuapp.com/
-- | --
Basic認証のIDとパスワード |  ID: admin  PW: 2222
出品者用のメールアドレスとパスワード | email: hoge@example.com  PW: 11tanuki
購入者用のメールアドレスとパスワード | email: hogehoge@example.com  PW: 11tanuki

**Comment by soll02solglas** [comment]
@ezurechan さん、大変お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] エラーハンドリングの際、重複したエラーメッセージが表示されないこと
→現状ユーザー新規登録ページでエラーメッセージが重複して表示されています。
<img width="504" alt="スクリーンショット 2022-07-12 9 49 12" src="https://user-images.githubusercontent.com/30042165/178384873-db51eda5-01f1-48be-b6f4-40b12f3f7e55.png">

- [ ] ページ下部の「もどる」ボタンを押すと、編集途中の情報は破棄され、商品詳細表示ページに遷移すること
「戻る」ボタンを押しても編集画面の上部に戻るだけで、詳細ページに遷移しません。

- [ ] ログイン状態の場合でも、自身が出品していない売却済み商品の商品購入ページへ遷移しようとすると、トップページに遷移すること
→売却済み商品であっても購入ページのURLを直接入力すると購入ページに遷移できてしまいます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
@ezurechan さん、修正とご提出ありがとうございます‼︎
動作の確認をしたところ、前回お伝えした点については一部を除き修正が確認できました。ありがとうございます。
引き続き、修正していただきたい箇所がございましたので、以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **ページ下部の「もどる」ボタンを押すと、編集途中の情報は破棄され、「商品詳細表示ページ」に遷移するよう修正しましょう**
「もどる」ボタンをクリックしても、商品詳細表示ページに遷移できない状態です。

https://user-images.githubusercontent.com/54050089/178445629-7eecae3d-6d3b-4fbd-9892-287fa06b2c90.mov

[補足]
商品の販売利益が正しい数字ではありません。必須要件とはなっておりませんが、可能であれば正しい数字が表示されるよう修正しましょう。
<img width="538" alt="スクリーンショット 2022-07-12 17 23 13" src="https://user-images.githubusercontent.com/54050089/178446933-c7ee7838-6dbf-493d-90a9-48c31b112b87.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by soll02solglas** [comment]
@ezurechan さん、フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/7680

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![lgtm_01](https://user-images.githubusercontent.com/30042165/178453287-0bcdb3d2-1b0f-40b2-9b5e-b8b3e9240668.png)
